### ISSUE TITLE
add sync job for abax-minuba

### ISSUE THREAD

**Issue by braaar** [getbranches/conf#187]
We should add a cron job that runs every so often and performs a sync operation. Not immediately urgent, but something we want eventually

See the abax-procore cron job for inspiration:

https://github.com/getbranches/conf/blob/021cf06f6253132f28c225455d329ccc9fbc4f4b/resources/kubernetes/deployments/abax-procore.ts#L35-L64

**Comment by simenandre** [comment]
Done!
