### ISSUE TITLE
We need `simenandre/setup-gke-gcloud-auth-plugin`

### ISSUE THREAD

**Issue by simenandre** [getbranches/conf#42]
Some builds are failing, we probably need `simenandre/setup-gke-gcloud-auth-plugin`.

**Comment by braaar** [comment]
What does this mean?

**Comment by simenandre** [comment]
Sorry, I'm unclear. Let me link some of the builds …

**Comment by simenandre** [comment]
https://github.com/getbranches/conf/actions/runs/4955613565/jobs/8865166268?pr=41
